// <auto-generated />
namespace MingaDigital.App.EF
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initial : IMigrationMetadata
    {
        //private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201504071408326_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1WzXLTMBC+M8M7aHQuVtP2AB0HJiQt04G0nbpwV+yNq0GWjLXuNM/GgUfiFVjFf4md0FI4MLnE0u6n3W+/Xenn9x/hu4dMs3sonLJmzEfBIWdgYpsok455ictXr/m7ty9fhGdJ9sC+NHbH3o48jRvzO8T8VAgX30EmXZCpuLDOLjGIbSZkYsXR4eEbMRoJIAhOWIyFN6VBlcH6gz6n1sSQYyn13CagXb1OO9EalV3KDFwuYxjzOUUmZypVKHUwyfPg7JyziVaSQolALzmTxliUSIGefnYQYWFNGuW0IPXtKgeyW0rtoE7gtDN/ai6HRz4X0Tk2UHHp0GZ/CDg6rskRffdnUcxb8oi+M6IZVz7rNYVjPolR3dMSZ/3DTqe68Ia7GPYoClzQeB+wvs1Bqw2SkP8dsGmpsSxgbKDEQuoDdl0utIo/wurWfgUzNqXWm8FSuLS3tUBL14XNocDVDSzrFC4SzsS2n+g7tm4bPlVyFwaPjzi7pMPlQkOrhQ0iIrQFfAADhURIriUiFMZjwJrN7dND0XE8ZJ6EjVIRUh3HnD78GjzgjgqQWusiUM2xKKFHT4UZAQ6K2cVQNUHQbe0Ktg2razRRdVrTkWJPS4ZzmedU+40WrVdYVPXn9FX057rNKgwRux3ybaNtT6ICyRR6u3Q0RXquCocziXIhfVmnSTYw2yzCHoKbk3o898XZ0d44+P91qYdzKtgH1LF4TollpLN1jtDGsz+GekpKLYsdmp9aXWam+laDvqkq3Tu5n6MYJNnrvT5pv9Nb36Q9vdVdT19hXevH74VB8SsTzoiWe5X4wl/mqfumu5W5NGoJDqt5xN8EJ8God5f8P3NdOJfoJw73Z0zVoToen6qqnarK4Alnjw7OwdR9/iQd9vo/mJWVZMY8X99UlFwVrPzbYToUcSg2n0DhDJxKOwj/IDIQe610oI3NhVnaphCU32ZEjUmvTnNAmRBNkwLVkpKh7Ricozbj7IvUJZmcZQtILsxViXmJE+cgW+itfEPx+/PXN8Z2zOFV7r/cv0iBwlSUAlyZ96XSSRv3+Q4d7YHwiqnFSVHRs5Dg0lWLdGnNE4Fq+maQg/HSvoUs1wTmrkwk7+E5sdHN/wlSGa+a0bQf5PFCbNMezpRMC5m5GqPz98964d/1b38BSPIKsAkMAAA="; }
        }
    }
}
